### ISSUE TITLE
Where_index_of_n_is_odd incorrectly named

### ISSUE THREAD

**Issue by amitsarna** [walkhard/linq-exercises#11]
Where_index_of_n_is_odd should be called Where_index_of_n_is_even (or the Assert should be changed). 

Also         public void Where_n_quare_minus_2_times_n_is_greater_than_n()
should be 'square' not 'quare'

Where_string_ends_with_uppercase_t is also incorrectly named, it should be lowercase_t

**Comment by zbma** [comment]
Thanks, I'll fix it in a moment.
