### ISSUE TITLE
fantastic!

### ISSUE THREAD

**Issue by benkoshy** [walkhard/linq-exercises#2]
Hi

thank you for these exercises.

These are really great.

Is it possible to create more comprehensive tests without the hints?

I only saw some 16 tests and they only cover first, firstordefault and last etc. - which are basically the same thing.

Perhaps once I learn Linq properly I will add to the test suite here.

rgds

Ben

**Comment by zbma** [comment]
Hi @BKSpurgeon 

I'm really glad you liked them. This projecte was kind of ditched, but since there's some interest I decided to add some more exercises soon. 

Check back soon.

**Comment by benkoshy** [comment]
Hi @walkhard friend you are on a winning wicket with this set of exercises! believe me. 

I've already written some partioning exercises (you should see the pull request come through) and i want to write some "ordering" exercises as well over the next couple of weeks - if you're happy to take contributions: i'd love to help out. bit by bit we can build quite a comprehensive and awesome place.

rgds
Ben
