### ISSUE TITLE
Aggregate_Secret_formula incorrect?

### ISSUE THREAD

**Issue by DavidSSL** [walkhard/linq-exercises#4]
I might have misunderstood the algorithm

>  // secret formula is as follows
>  // start with 256
>  // for each person take the day of her/his birth date
>  // if this day is bigger than 15, then substract 10 from it
>  // else add 5 to it
>  // and add resulting number to your aggregate

But from my understanding, there is no way that if we start with 256 we'll end up with a smaller number i.e. 48. Can you please provide more information about what the exercise is about?

**Comment by zbma** [comment]
@DavidSSL Indeed, I was playing with it and I've entered incorrect number, should be 296. It's fixed now, thanks!
